Daniil/screen when day started
Stas-Buzunko/top-notch-productivity pull request #6
Opened 2017-05-27 17:45 UTC by Xirisss

screen when day started

2017-06-01 11:05 UTC, Stas-Buzunko requested changes

2017-06-01 11:05 UTC, Stas-Buzunko commented on src/components/NewActivityList.js
>      firebase.database().ref('/users/' + userId + '/settings').once('value').then(snapshot => {
1) i'd like to see you checking in snapshot is not null before using it
if (snapshot.val() !== null) {

2) let's decide to use it like this
```
const object (you can name it as you want) = snapshot.val()
if (object !== null) {
 doSomething
}
```

2017-06-01 11:05 UTC, Stas-Buzunko commented on src/components/NewActivityList.js
>        const currentRate = (snapshot.val().currentRate * 0.4)
why not name it money to use shorthand syntax?

2017-06-01 11:05 UTC, Stas-Buzunko commented on src/components/NewActivityList.js
> +        workspace: snapshot.val().workspace,
when u have the same key and value it feels good to use spread + shorthand syntax
```
const { workspace } = object
this.setState({ workspace })
```
it's the same for other keys

2017-06-01 11:05 UTC, Stas-Buzunko commented on src/components/NewActivityList.js
>        if (snapshot.val().startedAt + 86400000 > moment()) {
what if snapshot.val() is null?
startedAt from null?

2017-06-01 11:05 UTC, Stas-Buzunko commented on src/components/NewActivityList.js
>        if (snapshot.val().startedAt + 86400000 > moment()) {
add check for null

2017-06-01 11:05 UTC, Stas-Buzunko commented on src/components/NewActivityList.js
>            hours: snapshot.val().hours,
spread + shorthand

2017-06-01 11:05 UTC, Stas-Buzunko commented on src/components/NewActivityList.js
> +    .then((response) => {
can be refactored to
```
.then(response => this.setState({ time: response.data.total_grand  }))
```

2017-06-01 11:05 UTC, Stas-Buzunko commented on src/components/NewActivityList.js
> +        timeWorkedBefore: timeWorkedBefore
key = value => shorthand

2017-06-01 11:05 UTC, Stas-Buzunko commented on src/components/NewActivityList.js
> +      timeWorkedBefore,
let's refactor these 2 requests to firebase
there are 2 ways
1) you want to send 2nd request after first is saved - use .then() then
2) you want to save at the same time, then we can do it in 1 request, 
https://firebase.google.com/docs/database/web/read-and-write#updating_or_deleting_data

2017-06-01 11:05 UTC, Stas-Buzunko commented on src/pages/SettingsPage.js
> +        email: snapshot.val().email,
check for snapshot !== null + spread + shorthand

2017-06-01 11:08 UTC, Stas-Buzunko requested changes

2017-06-01 11:08 UTC, Stas-Buzunko commented on src/components/CountDown.js
> +      const startedAt = this.props.startedAt;
spread

2017-06-01 11:08 UTC, Stas-Buzunko commented on src/components/NewActivityList.js
> +      if (snapshot.val().currentRate) {
if snapshot.val() is null, does null.currentRate will break the app?
check what happens when you try to use key from null

2017-06-01 11:08 UTC, Stas-Buzunko commented on src/components/NewActivityList.js
> +      if (snapshot.val().currentRate) {
.then() can be refactored to 1-3 lines

2017-06-01 11:08 UTC, Stas-Buzunko commented on src/pages/SettingsPage.js
> +    const { uid } = this.props.user
:+1:

2017-06-01 16:04 UTC, Xirisss commented on src/components/NewActivityList.js
>      firebase.database().ref('/users/' + userId + '/settings').once('value').then(snapshot => {
done

2017-06-01 16:05 UTC, Xirisss commented on src/components/NewActivityList.js
>        const currentRate = (snapshot.val().currentRate * 0.4)
done

2017-06-01 16:17 UTC, Xirisss commented on src/components/NewActivityList.js
>        if (snapshot.val().startedAt + 86400000 > moment()) {
done

2017-06-01 16:20 UTC, Xirisss commented on src/components/NewActivityList.js
> +    .then((response) => {
done

2017-06-01 16:42 UTC, Xirisss commented on src/components/NewActivityList.js
> +        workspace: snapshot.val().workspace,
done

2017-06-01 16:44 UTC, Xirisss commented on src/components/NewActivityList.js
>            hours: snapshot.val().hours,
done

2017-06-01 16:46 UTC, Xirisss commented on src/components/NewActivityList.js
> +        timeWorkedBefore: timeWorkedBefore
done

2017-06-01 17:02 UTC, Xirisss commented on src/components/NewActivityList.js
> +      timeWorkedBefore,
done

2017-06-01 17:06 UTC, Xirisss commented on src/pages/SettingsPage.js
> +        email: snapshot.val().email,
done

2017-06-01 17:09 UTC, Xirisss commented on src/components/CountDown.js
> +      const startedAt = this.props.startedAt;
done

2017-06-01 17:15 UTC, Xirisss commented on src/components/NewActivityList.js
> +      if (snapshot.val().currentRate) {
added:
const snapshotval = snapshot.val()
if if (snapshotval !== null) {
   ...
}

2017-06-05 15:42 UTC, Stas-Buzunko approved these changes

2017-06-05 15:42 UTC, Stas-Buzunko commented on src/components/CountDown.js
> +      this.calculationTime(left)
you call calculationTime in both cases, how about only setting "left" in if and then call calculationTime?

2017-06-05 15:53 UTC, Xirisss commented on src/components/CountDown.js
> +      this.calculationTime(left)
done

2017-06-05 15:57 UTC, merged